### ISSUE TITLE
Duplicates and incorrect entries

### ISSUE THREAD

**Issue by MammothJerk** [JasonHHouse/Gaps#103] opened 2020-01-09 07:38 UTC
**Describe the bug**

Several items on the list i already own, and several of the items show up multiple times in the same search

**To Reproduce**

Go to the WebUI
input TMDB key
Click on Plex
input plex ip, port, token
click next
tick the box of the library to search
click next
let gaps search for the missing items

now it brings up duplicates and multiples of the same movie.

**Expected behavior**

gaps should only show missing items from my plex library

**Screenshots**

![](https://i.imgur.com/fudtvUd.png)

![](https://i.imgur.com/yUTAMi2.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: firefox nightly
 - Gaps Version: 0.1.4

**Additional context**

Running on docker in unraid

----------------

I've already added 200+ movies thanks to this awesome script but this is the only problem i seem to run in to, good job!

**Comment by JasonHHouse** [comment] 2020-01-09 09:44
This appears to be a duplicate of https://github.com/JasonHHouse/Gaps/issues/96
I'm working it currently.

**Comment by JasonHHouse** [comment] 2020-01-10 01:21
Give this a try
https://github.com/JasonHHouse/Gaps/releases/tag/v0.1.5

**Comment by MammothJerk** [comment] 2020-01-10 10:12
i apparently had an issue within plex that certain movies showed as their scene names, refreshing the metadata renamed them to their correct title and the false positives stopped.

0.1.5 no longer threw duplicates at me and it seems to work perfectly fine now, thanks!

**Comment by JasonHHouse** [comment] 2020-01-12 01:17
Sweet, glad to hear it!

**Closed by JasonHHouse** 2020-01-12 01:17 UTC
Labels: bug
