### ISSUE TITLE
Scheduled scan not updating Missing UI and scanning libraries twice. 

### ISSUE THREAD

**Issue by g4m3r7ag** [JasonHHouse/gaps#185] opened 2020-10-03 17:32 UTC
**Describe the bug**
After deleting all stored data, setting up Plex server, TMDB API, schedule, and notifications again, after the next daily scheduled scan runs, the UI for missing shows no items, however the RSS has the list of missing items so they are logged. The Plex Libraries UI does populate all the movies after the scheduled scan. 

Daily scheduled scan, according to my notifications, run through the following process. TMDB connection is verified. Connection to the Plex Server is verified. It then scans each of the Plex libraries twice. It then scans each library against TMDB for Collection info twice. 

**To Reproduce**
1. Delete all stored data from the advanced settings. 
2. Reconfigure TMDB API, Plex Server, set schedule for daily scan, configure preferred notification method (I used pushover)
3. Wait for daily scheduled scan to run at 04:00, do not run a manual scan. 
4. After daily scan has completed, the libraries page will be populated for each library showing the items on the Plex server. However the missing page will show Mind the Gap warning on each library indicating nothing has been scanned. However the RSS page will be populated for the missing movies. 
5. Reviewing the notifications received after the scan started at 4AM should show all libraries being scanned twice. Both the plex scan, as well as the TMDB scan.

**Expected behavior**
Missing UI should update from daily scheduled runs. Libraries should only be scanned once. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu 20.04
 - Browser: Latest Chrome
 - Gaps Version 0.8.2 (interestingly not on the releases page) (running in docker on an Ubuntu 18.04 host)

**Additional context**

I originally did the delete all stored data trying to resolve the libraries being scanned twice issue thinking something may be corrupted/doubled up in the stored config. This led me to discover the Missing UI not updating from the scheduled scan (I've only tested a daily scan). I'm sure the missing UI would update if I ran a scheduled scan, but that makes me wonder if it's created with a manual scan, and the scheduled scan finds new items, will it update the UI? 

I haven't tried deleting the container and removing it's data directory as I assumed the delete all stored data option would be similar but that would be my next step if your not able to replicate. 

I tailed the container logs last night while the scan was running and can verify it scanned my movies library against TMDB twice that it wasn't just sending the notifications twice. I found no way to export logs in GAPS and I haven't found a way to export logs from the docker container to a text file to upload, if someone could point me in the right direction on how to do that then I can upload logs.

**Comment by JasonHHouse** [comment] 2020-10-05 00:52
I tested and cannot reproduce the error. Without logs, I won't be able to help.

**Comment by g4m3r7ag** [comment] 2020-10-05 01:01
What's the best way to export the logs from the container? I have no problem doing a delete all data again and waiting for the scheduled scan to go, just not sure how to get the logs. When I do a "docker container logs GAPS" there's way too much it just rolls off the SSH terminal.

**Comment by JasonHHouse** [comment] 2020-10-05 01:11
It's supposed to be a lot. Just copy it to a file, zip it up, and attach it.

**Comment by g4m3r7ag** [comment] 2020-10-05 17:15
[GAPS.zip](https://github.com/JasonHHouse/gaps/files/5328961/GAPS.zip)

Hopefully I redacted everything that needed to be. Starting at 04:00 it scanned each plex library for content twice. This isn't that big of deal as it only takes a couple seconds for it to scan the library. But at 04:00:28:582 it started scanning TMDB for collection info and proceeded to scan each library twice not finishing until almost 07:00. 

Before pulling the logs I also navigated to the Movies page for each library in GAPS and it displayed the content that currently exists on the server. However when navigating to the Missing page for each library it shows the error as if a scan was never run. But checking the RSS for each library shows it did indeed run.

**Comment by JasonHHouse** [comment] 2020-10-07 14:36
I saw a few errors in your log. I think I have it fixed for you. I pushed to the alpha docker if you want to try that. 
`docker pull housewrecker/gaps:alpha` and let me know if that fixes it.

**Comment by g4m3r7ag** [comment] 2020-10-07 16:44
Updated to the alpha image and the Missing UI is populated now. I will see if it scans the libraries twice on the daily 4am run and report back.

**Comment by g4m3r7ag** [comment] 2020-10-08 17:50
Scheduled scan is still scanning all the libraries twice. Both when it scans for existing movies on the Plex server, and when it scans TMDB for collection info. I've attached another set of logs from the alpha build. It actually scanned TMDB for collection info on the same library back to back, but this only happened for the one library the rest were random it seems so I assume that was just coincidence. 

It scanned library 14 at 04:00:28.106 and after finishing immediately scanned library 14 again at 04:02:49.246

[GAPS.2020.10.08.zip](https://github.com/JasonHHouse/gaps/files/5350461/GAPS.2020.10.08.zip)

**Comment by JasonHHouse** [comment] 2020-10-08 23:48
Please send the gaps.properties.

**Comment by g4m3r7ag** [comment] 2020-10-08 23:58
Attached


[gaps.zip](https://github.com/JasonHHouse/gaps/files/5351803/gaps.zip)

**Comment by JasonHHouse** [comment] 2020-10-09 02:11
I'm not sure why this is happening but I do have some ideas. I pushed an update on alpha to try. Let me know.

**Comment by g4m3r7ag** [comment] 2020-10-09 08:13
The version number didn't increase on the about page but watchtower recreated the container right about the time of your comment so I'm assuming it updated, and it's still scanning everything twice. I can pull the logs again later today after it finishes scanning. I'm assuming the gaps.properties shouldn't have changed and you won't need that again?

**Comment by g4m3r7ag** [comment] 2020-10-09 22:10
Sorry it took me awhile to get these together, been a crazy day. I noticed two things

1) Whatever changes you made greatly increased the speed of the scan. Previously it was taking nearly 3 hours to get through scanning each library twice, last night it only took an hour. 

2) My pushover token/user no longer needs to be redacted from the logs. 

Attached are the ones from last nights much faster scan, it still went through all libraries twice though. 

[GAPS.2020.10.09.zip](https://github.com/JasonHHouse/gaps/files/5357816/GAPS.2020.10.09.zip)

**Comment by JasonHHouse** [comment] 2020-10-11 08:43
I think I found it. Please pull alpha and test again.

**Comment by g4m3r7ag** [comment] 2020-10-11 13:39
Looks like watchtower pulled the new image in the middle of today's scan, I'll update tomorrow with how the next one goes.

**Comment by g4m3r7ag** [comment] 2020-10-12 08:42
That did the trick, only scanned Plex and TMDB once.

**Comment by g4m3r7ag** [comment] 2020-10-12 17:05
Hmm, the list of owned/missing on a collection is missing on the UI page, not sure if this is related to a change you made on this issue or something else. This is the alpha build. 

![missing](https://user-images.githubusercontent.com/46694420/95772974-9bdef600-0c8b-11eb-835e-32e69739d5ac.JPG)

**Comment by JasonHHouse** [comment] 2020-10-13 04:21
Good catch. I think it's from an older bug but I fixed it in alpha and pushed.

**Comment by g4m3r7ag** [comment] 2020-10-13 04:38
Pulled the latest image, it is fixed.

**Comment by JasonHHouse** [comment] 2020-10-13 05:02
Awesome, I'll get it merged in mainline.

**Closed** 2020-10-13 05:13 UTC
Labels: bug
