### ISSUE TITLE
Folder Option Still disabled...

### ISSUE THREAD

**Issue by Marthisdil** [JasonHHouse/Gaps#118] opened 2020-05-13 01:36 UTC
When will it be enabled?  Being able to search based on filename would be more helpful than dealing with plex libraries.

**Comment by JasonHHouse** [comment] 2020-05-13 03:11
Duplicate of https://github.com/JasonHHouse/Gaps/issues/110

**Comment by JasonHHouse** [comment] 2020-05-13 03:12
Duplicate of https://github.com/JasonHHouse/Gaps/issues/110

**Closed by JasonHHouse** 2020-05-13 03:12 UTC
Labels: bug
