### ISSUE TITLE
Can't import RSS List into Radarr v3

### ISSUE THREAD

**Issue by lastb0isct** [JasonHHouse/gaps#201] opened 2021-01-04 00:29 UTC
**Describe the bug**
Getting an error when trying to import my GAPS RSS into Radarr v3

**To Reproduce**
Attempting to put the GAPS docker UTL into the Radarr v3 list and get and error

**Expected behavior**
Expected to be able to import the rss feed!

**Desktop (please complete the following information):**
 - RHEL8 running Docker on the :latest tag for GAPS

**Additional context**
The error in Radarr is as follows:

```
021-1-3 16:25:14.1|Warn|HttpClient|HTTP Error - Res: [GET] http://192.168.1.35:8484/rss/85392e1164a626839df6e4fc0525e79cd00600e2/8: 406.NotAcceptable
<Map><timestamp>2021-01-04T00:25:14.052+00:00</timestamp><status>406</status><error>Not Acceptable</error><message></message><path>/rss/85392e1164a626839df6e4fc0525e79cd00600e2/8</path></Map>
2021-1-3 16:25:14.1|Warn|RSSImport|Unable to connect to list

[v3.0.0.4204] NzbDrone.Common.Http.HttpException: HTTP request failed: [406:NotAcceptable] [GET] at [http://192.168.1.35:8484/rss/85392e1164a626839df6e4fc0525e79cd00600e2/8]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchImportListResponse(ImportListRequest request) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 173
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 157
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187
<Map><timestamp>2021-01-04T00:25:14.052+00:00</timestamp><status>406</status><error>Not Acceptable</error><message></message><path>/rss/85392e1164a626839df6e4fc0525e79cd00600e2/8</path></Map>
```
Is it specific to the timestamp as stated here?! What settings should I have defined in my system to allow this? I'm currently using my local TZ as an environment variable.

**Comment by JasonHHouse** [comment] 2021-01-04 01:40
Can a browser display the RSS from the gaps URL? ` http://192.168.1.35:8484/rss/85392e1164a626839df6e4fc0525e79cd00600e2/8`

**Comment by lastb0isct** [comment] 2021-01-04 01:59
Yes, I can browse the entire webui just find and the rss lists as just a giant feed, as it should I believe?

**Comment by JasonHHouse** [comment] 2021-01-04 02:00
Seems fine to me. It might be a docker networking issue with Radar? 406 errors are usually not very easy to resolve.

**Comment by lastb0isct** [comment] 2021-01-04 03:54
Radarr can connect to everything else as well...I'll have to take a look deeper then.

**Comment by JasonHHouse** [comment] 2021-01-04 04:18
Can you take a screenshot of your RSS configuration in Radar for Gaps and post it for me to check out? I can compare to my own to try and help.

**Comment by SteffanCline** [comment] 2021-01-04 09:12
I too am having the same issue. Plex, Gaps and Radarr are all on the same machine. I am able to resolve the RSS feed on the same machine fine. When adding it to Radarr, I get an error 

2021-1-4 02:07:16.9|Warn|RSSImport|Unable to connect to list

[v3.0.1.4345] NzbDrone.Common.Http.HttpException: HTTP request failed: [406:NotAcceptable] [GET] at [http://127.0.0.1:8484/rss/cedea55fb25a3b24cb05f44c912c36ce967bc968/1]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchImportListResponse(ImportListRequest request) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 173
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 157
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187
<Map><timestamp>2021-01-04T09:07:16.964+00:00</timestamp><status>406</status><error>Not Acceptable</error><message></message><path>/rss/cedea55fb25a3b24cb05f44c912c36ce967bc968/1</path></Map>


2021-1-4 02:07:16.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to list, check the log for more details

**Comment by JasonHHouse** [comment] 2021-01-04 09:33
Use a Custom List, not an RSS list.

**Comment by SteffanCline** [comment] 2021-01-04 15:36
Upon changing to a custom list, the adding error goes away but then I see a bunch of errors like this in Radarr. How can it not find the movies when it has the tmdb info from Gaps?

2021-1-4 08:30:12.4|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v3.0.1.4345] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 302


2021-1-4 08:30:12.4|Warn|SkyHookProxy|Sequence contains no elements

[v3.0.1.4345] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424


2021-1-4 08:30:12.4|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v3.0.1.4345] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 302


2021-1-4 08:30:12.4|Warn|SkyHookProxy|Sequence contains no elements

[v3.0.1.4345] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424


2021-1-4 08:30:12.4|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v3.0.1.4345] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 302

**Comment by lastb0isct** [comment] 2021-01-04 16:00
Here is what the list being added to radarr looks like:

![rss](https://user-images.githubusercontent.com/19312164/103553885-ef17ad80-4e62-11eb-9be2-112e88212eb7.png)

**Comment by lastb0isct** [comment] 2021-01-04 16:08
Ah, think I got it -- Custom List in v3!!

**Comment by lastb0isct** [comment] 2021-01-04 16:20
Just need to figure out how to actually check if the list is imported properly and that it is bringing these new movies in

**Comment by SteffanCline** [comment] 2021-01-04 17:06
Radarr v3 doesn't have viewable lists like v2 did. How can I tell what's going on? I don't see any new movies being searched for or appearing when I filter on missing movies.

**Comment by JasonHHouse** [comment] 2021-01-05 00:30
I think you can go to the list of all your movies and search for a movie gaps recommends that you don't have. That should show it's added and monitored.

**Comment by lastb0isct** [comment] 2021-01-05 01:12
Yep, i've confirmed that the movies did not get added, same as @SteffanCline for me.  The logs show this, which show that it is searching for a '' string for every entry, so the TMDB # is not being passed along:

```
2021-1-4 17:10:36.0|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v3.0.0.4204] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 302


2021-1-4 17:10:36.0|Warn|SkyHookProxy|Sequence contains no elements

[v3.0.0.4204] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424
```

**Comment by JasonHHouse** [comment] 2021-01-05 02:38
Can you attach your RSS feed from gaps as a file? I think it means there's a movie that gaps is recommending but doesn't have a TMDB id.

**Comment by lastb0isct** [comment] 2021-01-05 03:21
[gaps_rss.txt](https://github.com/JasonHHouse/gaps/files/5767920/gaps_rss.txt)

**Comment by JasonHHouse** [comment] 2021-01-05 03:38
That's not valid JSON. It should contain quotes and colons to make the objects.

**Comment by SteffanCline** [comment] 2021-01-05 04:06
[gaps.txt](https://github.com/JasonHHouse/gaps/files/5768057/gaps.txt)
Mine has quotes but has the same errors. Is this a bug in the Gaps? I am using the latest distro you have posted.

**Comment by lastb0isct** [comment] 2021-01-05 04:27
Sorry, the one that @SteffanCline posted is exactly like mine...not sure where I grabbed that other one.

**Comment by JasonHHouse** [comment] 2021-01-05 12:28
I looked into the Steven Lu RSS feeds https://github.com/sjlu/popular-movies and it looks like everything should work. I also looked into the Radarr code and found the imdb_id. tvdb_id is a bug and should be tmdb_id, it might be causing the issue, so I'll push a change but I'm not positive that it is.

**Comment by lastb0isct** [comment] 2021-01-05 16:39
Anyway to pull that directly right now with docker?  I've never pulled a non-normal tag...

**Comment by JasonHHouse** [comment] 2021-01-05 22:47
@lastb0isct No, I'll push to latest. I should have it up later today.

**Comment by SteffanCline** [comment] 2021-01-06 05:56
Will this be a new release?

**Comment by JasonHHouse** [comment] 2021-01-07 04:21
Yes, latest will be updated

**Comment by JasonHHouse** [comment] 2021-01-07 11:16
I changed my mind and pushed under a versioned branch. Please test with `docker pull housewrecker/gaps:v0.8.8`

**Comment by lastb0isct** [comment] 2021-01-07 15:53
I'm getting the same behavior:

```
2021-1-7 07:51:04.0|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v3.0.0.4204] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 424
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 302
```
RSS Feed:
```
[{"imdb_id":"tt5565634","release_date":2018,"tvdb_id":445710,"title":"Children of the Corn: Runaway","poster_path":"https://image.tmdb.org/t/p/w185//mibVNUTPTrF8pZeOgdUkkU21KXG.jpg"},{"imdb_id":"tt5257554","release_date":2017,"tvdb_id":384978,"title":"Puppet Master: Axis Termination","poster_path":"https://image.tmdb.org/t/p/w185//hE4wGidAJ2yppEkZsY7QmWHJaWR.jpg"},{"imdb_id":"tt0095895","release_date":1988,"tvdb_id":24348,"title":"Powaqqatsi","poster_path":"https://image.tmdb.org/t/p/w185//onKAIjxeFpEJ5l1Ym2rCVduVOYZ.jpg"},
```
Looks like the id is still set as tvdb_id? Confirmed i'm running housewrecker/gaps:v0.8.8

**Comment by SteffanCline** [comment] 2021-01-07 22:04
I don't use docker. How can I pull this to test?

**Comment by SteffanCline** [comment] 2021-01-08 04:07
Ok, I was able to manually download and build it. After copying the new jar to my gaps folder and launching it, I can confirm it's still has them as tvdb. Do I need to erase all the data and regenerate it?

[{"imdb_id":"tt5257554","release_date":2017,"tvdb_id":384978,"title":"Puppet Master: Axis Termination","poster_path":"https://image.tmdb.org/t/p/w185//hE4wGidAJ2yppEkZsY7QmWHJaWR.jpg"},{"imdb_id":"tt1346302","release_date":2009,"tvdb_id":84598,"title":"Pimpin' Pee Wee","poster_path":"https://image.tmdb.org/t/p/w185//fFGm3qBLJVRbMRrTh2TF5ul5N9u.jpg"}, ... ]

**Comment by JasonHHouse** [comment] 2021-01-08 04:30
You need to pull or checkout this branch. The code isn't merged. https://github.com/JasonHHouse/gaps/tree/issue/rss_fix%23201

**Comment by SteffanCline** [comment] 2021-01-08 04:36
I manually downloaded and built the jar. I had to delete all the data and start over. Now it's working better but for the sake of consistency, it may be of value to wrap the text going into the json encoder with a trim. If you notice below, you'll see "tmdb_id" and " tmdb_id ". Not yet sure if that matters as it's searching for collections on about 4500 movies.

[{"imdb_id": "tt0092857", "release_date": 1987, "tmdb_id": 26263, "title": "Death Wish 4: The Crackdown", "poster_path": "https://image.tmdb.org/ t / p / w185 // 8yVdLJa5ywqwNAKU1nmUtDJlx8b.jpg "}, {" imdb_id ":" tt1630626 "," release_date ": 2011," tmdb_id ": 58443," title ":" Blue Crush 2 "," poster_path " : //image.tmdb.org/t/p/w185//zSwELTIawuuaknMSsmWBXb0avp8.jpg "}, {" imdb_id ":" tt0106544 "," release_date ": 1993," tmdb_id ": 38955," title ":" Project S "," poster_path ":" https://image.tmdb.org/t/p/w185//zOwms83j8Z5HrseSrbaxgxQ67ad.jpg "}]

**Comment by JasonHHouse** [comment] 2021-01-08 04:47
Good catch! I'll add that in and I'm glad it worked.

**Comment by SteffanCline** [comment] 2021-01-08 04:48
I'm letting it build up a few collections then kick off the list import task in Radarr to see if it errors out or works.

**Comment by SteffanCline** [comment] 2021-01-08 04:54
We're not out of the woods yet. See the spot marked in bold. I think the title is supposed to be between there. ex: map movie MyMovie to a movie on The Movie DB...

2021-1-7 21:49:26.8|Warn|SkyHookProxy|Sequence contains no elements

[v3.0.1.4359] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 431


2021-1-7 21:49:26.8|Warn|SkyHookProxy|Couldn't map **movie  to a movie** on The Movie DB. It will not be added :(

[v3.0.1.4359] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 431
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 309


2021-1-7 21:49:26.8|Warn|SkyHookProxy|Sequence contains no elements

[v3.0.1.4359] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 431

**Comment by JasonHHouse** [comment] 2021-01-08 04:56
Do you have a record in the RSS with an empty TMDb id?

**Comment by SteffanCline** [comment] 2021-01-08 04:59
This is about 50% done. 
[gaps.txt](https://github.com/JasonHHouse/gaps/files/5785297/gaps.txt)

**Comment by JasonHHouse** [comment] 2021-01-08 05:12
Are you trying to add the RSS while gaps runs? If so, I would wait as the file gets updated a lot.

**Comment by SteffanCline** [comment] 2021-01-08 05:18
I'll try loading the RSS again in Radarr once Gaps finishes with my library. Looks like maybe 20 min then I'll reply back with the log.

**Comment by JasonHHouse** [comment] 2021-01-08 05:36
Sounds good.

**Comment by SteffanCline** [comment] 2021-01-08 05:50
Same errors. 
[radarr.txt](https://github.com/JasonHHouse/gaps/files/5785456/radarr.txt)
[gaps.txt](https://github.com/JasonHHouse/gaps/files/5785457/gaps.txt)

**Comment by JasonHHouse** [comment] 2021-01-08 07:00
I don't see anything wrong at first glance in that RSS. There are no padding issues and all the movies have ids and names. I'm reaching out to the Radarr team for help.

**Comment by SteffanCline** [comment] 2021-01-08 16:41
It appears to work if you use the StevenLu Custom list in Radarr. So, either the plain Custom List in Radarr is broke or the JSON needs to be adjusted to work with Custom List.

**Comment by lastb0isct** [comment] 2021-01-08 16:45
@SteffanCline  -- There is no way to edit the StevenLu Custom list in v3.  This is all that is shown
<img width="716" alt="Screen Shot 2021-01-08 at 08 44 45" src="https://user-images.githubusercontent.com/19312164/104041389-ceff2b80-518d-11eb-8150-94613e649556.png">

**Comment by SteffanCline** [comment] 2021-01-08 17:00
@JasonHHouse had said to use Custom List. That didn't work. The StevenLu list option does work. First go back and delete all your gaps data and then reconfigure it from scratch with the .0.8.8 version. Rerun your scan on your library which will regenerate your RSS feed. It's static so once created in the scan, it may not show the changes from the newer version. Do not proceed until the scan of your library is complete.

Once that's done and you have a new RSS feed generated, check it and you should see the tmdb_id rather than tvdb_id. If you have that, you're golden.

Delete those lists you have set up now in Radarr. Create a new list like what I show above. The reason mine says Gaps Import **2** is because the other one is a plan Custom List.

![Screen Shot 2021-01-08 at 9 50 36 AM](https://user-images.githubusercontent.com/1323544/104041913-fc9ca280-5196-11eb-87cc-533b53634f0e.png)

Once you have that in, it should work. I suggest you **don't** auto-add to your list as you may get hundreds of additions. I made this mistake once with Trakt. haha. Next go to Radarr > Movies > Discover. In the top right, click on Filter and select Custom Filter. Add a new filter. Label: Gaps, Filters: List, Contains, Click in the field and select your Gaps Import list. Save it. If your screen doesn't immediately fill up then go to your Radarr tasks and rerun the Import List task. Go back to Discover and you should see all of your Gaps matches populating the list. 

From there, go ahead and check those you want to actually add to your library. Scroll to the bottom and you'll see the options for the import and the submit button.

**Comment by lastb0isct** [comment] 2021-01-08 17:03
I see the stevenlu custom list now and didn't think to delete/rescan the rss.  Will try this! Thanks for the help

**Comment by SteffanCline** [comment] 2021-01-08 17:09
I tinkered with this a while and was surprised when it started working. The list type was the critical piece. 

Let me know how it comes out for you.

**Comment by JasonHHouse** [comment] 2021-01-08 23:02
Thanks for all the help on this @SteffanCline 

Let me know if this works for you @lastb0isct.

Once we're good, I'll merge and do a normal release.

**Comment by SteffanCline** [comment] 2021-01-08 23:11
@JasonHHouse, are we supposed to be using the StevenLu Custom or just regular Custom?

**Comment by JasonHHouse** [comment] 2021-01-08 23:13
In v2, it was StevenLu. I use a custom list in v3. But I'm talking to a Radarr dev to get information about the difference between the lists. I would prefer to just update gaps RSS feed to support either, if possible to prevent confusion in the future.

**Comment by SteffanCline** [comment] 2021-01-08 23:15
Who is StevenLu anyway?? haha. He has his own special interface protocol now? LOL

**Comment by JasonHHouse** [comment] 2021-01-08 23:17
LOL I don't know the details but I've seen his GitHub and website. That's where the original RSS format came from.

https://github.com/sjlu/popular-movies

https://s3.amazonaws.com/popular-movies/movies.json

https://movies.stevenlu.com/

**Comment by lastb0isct** [comment] 2021-01-09 00:20
Working now! I used the StevenLu Custom list and it's importing my movies! Thanks for all the troubleshooting and such.  I think we can close this ticket!

Do you know when the fix will be in :latest?

**Comment by lastb0isct** [comment] 2021-01-09 00:21
https://github.com/sjlu -- There he is! haha

**Comment by JasonHHouse** [comment] 2021-01-09 01:13
I'll close it once everything is merged and released. Glad to hear it's working for you.

**Closed** 2021-01-09 01:14 UTC
Labels: bug
