### ISSUE TITLE
Can't launch Gaps (Windows)

### ISSUE THREAD

**Issue by DarkSmileee** [JasonHHouse/gaps#200] opened 2021-01-03 18:27 UTC
Hi, I just downloaded the latest zip (Gaps v0.8.5).
I followed the tutorial : https://github.com/JasonHHouse/gaps/wiki/Windows

It installed it in C:\Program Files (x86)\Gaps whenever I click start.bat it launches a cmd screen and closes immediately.

**Comment by JasonHHouse** [comment] 2021-01-03 22:15
Open a file explorer, navigate to the folder gaps is in, right-click and press shift to open a terminal at that location. Run gaps and the window will remain open and tell you what the issue is.

**Comment by rockymtnpatriot** [comment] 2021-01-04 01:43
I too tried the latest install today. I ran the executable and bat file but when trying to access via the url I get the site can't be reached/localhost refused to connect. Here are the results you asked for above:
X:\server\GapsAsJar-0.8.5>startOnWindows.bat
"Running without SSL and without Login"
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jasonhhouse/gaps/GapsApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

I am running the latest version of Java 32 & 64 bit v.8 271

**Comment by JasonHHouse** [comment] 2021-01-04 01:45
Gaps requires Java 11. You can install from this OpenJDK link https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip.sha256

**Comment by rockymtnpatriot** [comment] 2021-01-04 01:50
Thanks, found the other thread on this similar topic from last summer mentioning the same thing.

**Comment by JasonHHouse** [comment] 2021-01-04 01:59
Sounds good. I'll close this but if you have other issues just open a new ticket. Thanks for using Gaps!

**Closed** 2021-01-04 02:00 UTC
